apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: go-hello-world
    docker:
      dockerfile: build/skaffold/Dockerfile
deploy:
  kubectl:
    manifests:
    - build/skaffold/k8s/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
