apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    docker:
      dockerfile: build/develop/Dockerfile
      noCache: false
    image: go-hello-world
deploy:
  kubectl:
    manifests:
    - deployments/develop/kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
